name: "Monorepo Package Mirror Action"
description: "Mirroring with support for ignoring private directories. Based on `pixta-dev/repository-mirroring-action`"
branding:
  icon: "grid"
  color: "yellow"
inputs:
  ssh_private_key:
    description: "SSH private key for ssh connection to the target repository"
    required: false
  target_repo_url:
    description: "Target url"
    required: true
  ssh_username:
    description: "Username for ssh connection"
    required: false
    default: "git"
  main_branch:
      description: "Main branch that will be copied"
      required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
